[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
build-utils = { path = "../build-utils" }
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
