[target.arm-unknown-linux-gnueabi]
linker = "arm-frc2023-linux-gnueabi-gcc"
rustflags = ["-C", "target-cpu=cortex-a9"]

[build]
target = "arm-unknown-linux-gnueabi"

[env]
LIBS_OUT_DIR = { value = "target/lib", relative = true }
