[package]
name = "math"
version = "0.1.0"
edition = "2021"

[dependencies]
impl-trait-for-tuples = "0.2.2"
nalgebra = "0.32.5"
hal-sys = { path = "../hal-sys", optional = true }

[features]
std = []
frc = ["dep:hal-sys"]
