name: rustdoc

on:
  push:
    branches:
      - main

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: cargo install cargo-make
      - name: Generate docs
        run: cargo make doc 
      - name: Deploy docs
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: target/arm-unknown-linux-gnueabi/doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
